name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests=2.24.0
  - pip=20.3.3
  - six
  - pip:
      - protobuf==3.20.*
      - numpy==1.23.4
      - wandb==0.10.21